# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nyoom-nvim = {
    pname = "nyoom-nvim";
    version = "f808500883ffc552b53a421139cc1915955759b7";
    src = fetchFromGitHub {
      owner = "nyoom-engineering";
      repo = "nyoom.nvim";
      rev = "f808500883ffc552b53a421139cc1915955759b7";
      fetchSubmodules = false;
      sha256 = "sha256-XzQB4bZeS2xTCEsUvPNi66901ZSI1k576oEFjTA54nU=";
    };
    date = "2023-11-05";
  };
}
